# Generated by Django 5.0.3 on 2024-04-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='booths',
            field=models.ManyToManyField(blank=True, null=True, to='branch.booth'),
        ),
        migrations.AlterField(
            model_name='branchnumber',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
